### ISSUE TITLE
Google Translate only doing the first line

### ISSUE THREAD

**Issue by barraged1** [uyjulian/Translation-Aggregator#4] opened 2019-06-21 03:01 UTC
Currently when sending a line through google it only translates/shows the first line of what is on your clipboard. 
![image](https://user-images.githubusercontent.com/49034318/59894685-84ea0580-93af-11e9-8837-cdd04673395a.png)

**Comment by uyjulian** [comment] 2019-06-21 05:39
duplicate of #3

**Closed by uyjulian** 2019-06-21 05:39 UTC
